player1=GameStateManager:GetPlayer(1);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("ArmyAssault");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("ArmyAssault");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("ArmyAssault");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("ArmyAssault");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("ArmyAssault");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,false);
card=CardManager:CreateNewCard("Mine");
player1:AddCard(card,true);


buff=BuffManager:CreateNewBuff("Mine");
Terrain:GetArea(7):AddBuff(buff);